### PR TITLE
add cache around launchtemplate API calls

### PR DESCRIPTION
**Pull request by akloss-terion**
A seemingly workable cache for the launch templates.  This really needs a refactor to move the loop invariants outside of the loop, but a dirty cache like this is a quick work-around.

### CODE REVIEW

**Comment by calizarr** [comment]
Oof, it feels dangerous to be forking kops in this respect. Although happy to be testing it out and see if it solves the `LaunchTemplate` no delete issue or that's a red herring all around.

**Review by calizarr — APPROVED** [review]
Cautiously LGTM as a test.

**Comment by akloss-terion** [comment]
I suspect it won't fix the LaunchTemplate issue we're having with dev-alpha, but it'll make iterating on it a lot easier to do.  I don't think I'd ask upstream to accept a hack like this, but I suspect refactoring kops to inject the templates in a sane way is kinda a lot of work.

**Comment by akloss-terion** [comment]
Newer kops still generate a lot of throttling with AWS, but much _less_ than it used to, so closing.

**Pull request closed without merging**
